### PR TITLE
The package was outdated and the example project was not working

### PR DESCRIPTION
**Pull request by mahanpyk**
- change "com.android.tools.build:gradle" and "kotlin_version" in build.gradle package and example
- change "distributionUrl" in gradle-wrapper.properties on the package and example
- change "compileSdkVersion" and "targetSdkVersion" in app/build.gradle

### CODE REVIEW

**Review by MoralCode — COMMENTED** [review]
while I haven't personally run or tested this, the diff seems reasonable/looks good to me.

**Comment by MoralCode** [comment]
I'll leave the final testing and merging to @Almoullim, but thanks for the contribution!

**Review by DavidIjsud — APPROVED** [review]

**Comment by DavidIjsud** [comment]
will this PR be merged?

**Comment by mahanpyk** [comment]
This PR get to the close pull request

**Pull request merged**
