### PR TITLE
Various changes (see description for details)

### PR DESCRIPTION
**Pull request by josxha**
- migrate from deprecated `pendantic` to `flutter_lints` and fix lints
- format code, structure package files, remove leftovers from before null safety
- remove IDE specific files (eclipse, jetbrains and vscode)
- remove pubspec.lock files (see https://dart.dev/guides/libraries/private-files#the-rules)
- make `Location` immutable, change time to `DateTime`
- update gradle to 7.6

### CODE REVIEW

**Comment by josxha** [comment]
removed more eclipse project files from the git repository, one of them is the .project file that caused the CI to fail.

**Comment by MoralCode** [comment]
Hello, apologies for the delay on getting to this. I approved a PR run to see if this passes CI.

Unfortunately I'm in a bit of a tough spot with regards to maintaining this repo (see my comments in #188), largely due to me being unable and/or out of time to thoroughly test each PR.

If i could get some more info on how this PR was tested (and maybe some community members to validate that the test procedure works) I'd feel a lot more confident merging this

**Comment by josxha** [comment]
Thanks for your response @MoralCode, I appreciate your cautiousness. I created this pull request while I was evaluating this package for my use case. 

I leave some additional notes if someone wants to take a look at the changes: 
Most changes have no implication on functionality and are either deleted IDE files or refactoring. The only breaking change is the change of `Location.time` to be a DateTime (previously int) for improved type safety.

**Comment by MoralCode** [comment]
does #208 address all the issues you had in this PR?

**Pull request closed without merging**
